include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint

  exclude:
    - "build/**"
    - "lib/firebase_options.dart"
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

  strong-mode:
    implicit-casts: false  # Запрет неявных кастов
    implicit-dynamic: false # Запрет неявного dynamic

  errors:
    # Легенда уровней:
    # ignore - полностью отключить
    # warning - предупреждение (не прерывает сборку)
    # error - ошибка (прерывает сборку)
    missing_required_param: error
    missing_return: error
    invalid_null_aware_operator: error
    prefer_null_aware_method_calls: error
    unawaited_futures: error
    deprecated_member_use: warning
    invalid_annotation_target: ignore
    implicit_call_tearoffs: ignore

  language:
    strict-casts: true     # Строгая проверка кастов
    strict-inference: true # Строгий вывод типов
    strict-raw-types: true # Строгая проверка raw типов

linter:
  rules:
    # Стиль кода
    prefer_const_constructors: true
    use_key_in_widget_constructors: true
    sort_child_properties_last: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    avoid_renaming_method_parameters: true
    avoid_catches_without_on_clauses: true
    prefer_final_locals: true
    require_trailing_commas: true
    unnecessary_lambdas: false
    type_annotate_public_apis: false
    avoid_types_on_closure_parameters: true
    prefer_relative_imports: true
    always_use_package_imports: false

    # ООП
    avoid_empty_else: true
    avoid_returning_null: true
    avoid_unused_constructor_parameters: true
    prefer_single_quotes: true
    slash_for_doc_comments: true
    type_init_formals: true

    # Безопасность
    avoid_shadowing_type_parameters: true
    await_only_futures: true
    curly_braces_in_flow_control_structures: true
    prefer_is_empty: true
    unnecessary_null_checks: true
    use_build_context_synchronously: true

    # Современные фичи Dart
    prefer_conditional_assignment: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_interpolation_to_compose_strings: true
    prefer_spread_collections: true

    # Чистота кода
    avoid_print: true           # Запрет debug-принтов
    avoid_classes_with_only_static_members: true
    unnecessary_this: true
    prefer_typing_uninitialized_variables: true
    unnecessary_nullable_for_final_variable_declarations: true

    # Форматирование
    lines_longer_than_80_chars: false # Отключено, т.к. работает с formatter
    prefer_double_quotes: false
    public_member_api_docs: false

formatter:
  page_width: 80

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options